In [1]:
from sklearn import datasets
import pandas as pd

In [2]:
boston=datasets.load_boston()

In [3]:
df=pd.DataFrame(boston.data)

In [4]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.593761,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063
std,8.596783,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000
75%,3.647423,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000

In [5]:
from sklearn import preprocessing

In [7]:
scaled_data=preprocessing.scale(boston.data)

In [8]:
df2=pd.DataFrame(scaled_data)

In [9]:
df2.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12
count,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02
mean,6.340997e-17,-6.343191e-16,-2.682911e-15,4.701992e-16,2.490322e-15,-1.145230e-14,-1.407855e-15,9.210902e-16,5.441409e-16,-8.868619e-16,-9.205636e-15,8.163101e-15,-3.370163e-16
std,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00
min,-4.177134e-01,-4.877224e-01,-1.557842e+00,-2.725986e-01,-1.465882e+00,-3.880249e+00,-2.335437e+00,-1.267069e+00,-9.828429e-01,-1.313990e+00,-2.707379e+00,-3.907193e+00,-1.531127e+00
25%,-4.088961e-01,-4.877224e-01,-8.676906e-01,-2.725986e-01,-9.130288e-01,-5.686303e-01,-8.374480e-01,-8.056878e-01,-6.379618e-01,-7.675760e-01,-4.880391e-01,2.050715e-01,-7.994200e-01
50%,-3.885818e-01,-4.877224e-01,-2.110985e-01,-2.725986e-01,-1.442174e-01,-1.084655e-01,3.173816e-01,-2.793234e-01,-5.230014e-01,-4.646726e-01,2.748590e-01,3.811865e-01,-1.812536e-01
75%,6.248255e-03,4.877224e-02,1.015999e+00,-2.725986e-01,5.986790e-01,4.827678e-01,9.067981e-01,6.623709e-01,1.661245e+00,1.530926e+00,8.065758e-01,4.336510e-01,6.030188e-01
max,9.941735e+00,3.804234e+00,2.422565e+00,3.668398e+00,2.732346e+00,3.555044e+00,1.117494e+00,3.960518e+00,1.661245e+00,1.798194e+00,1.638828e+00,4.410519e-01,3.548771e+00

In [11]:
from sklearn.linear_model import LinearRegression
clf=LinearRegression()

In [12]:
clf.fit(scaled_data,boston.target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [16]:
clf.predict(scaled_data)

array([30.00821269, 25.0298606 , 30.5702317 , 28.60814055, 27.94288232,
       25.25940048, 23.00433994, 19.5347558 , 11.51696539, 18.91981483,
       18.9958266 , 21.58970854, 20.90534851, 19.55535931, 19.2837957 ,
       19.30000174, 20.52889993, 16.9096749 , 16.17067411, 18.40781636,
       12.52040454, 17.67104565, 15.82934891, 13.80368317, 15.67708138,
       13.3791645 , 15.46258829, 14.69863607, 19.54518512, 20.87309945,
       11.44806825, 18.05900412,  8.78841666, 14.27882319, 13.69097132,
       23.81755469, 22.34216285, 23.11123204, 22.91494157, 31.35826216,
       34.21485385, 28.0207132 , 25.20646572, 24.61192851, 22.94438953,
       22.10150945, 20.42467417, 18.03614022,  9.10176198, 17.20856571,
       21.28259372, 23.97621248, 27.65853521, 24.0521088 , 15.35989132,
       31.14817003, 24.85878746, 33.11017111, 21.77458036, 21.08526739,
       17.87203538, 18.50881381, 23.9879809 , 22.54944098, 23.37068403,
       30.36557584, 25.53407332, 21.11758504, 17.42468223, 20.7893086 ,
       25.20349174, 21.74490595, 24.56275612, 24.04479519, 25.5091157 ,
       23.97076758, 22.94823519, 23.36106095, 21.26432549, 22.4345376 ,
       28.40699937, 26.99734716, 26.03807246, 25.06152125, 24.7858613 ,
       27.79291889, 22.16927073, 25.89685664, 30.67771522, 30.83225886,
       27.12127354, 27.41597825, 28.9456478 , 29.08668003, 27.04501726,
       28.62506705, 24.73038218, 35.78062378, 35.11269515, 32.25115468,
       24.57946786, 25.59386215, 19.76439137, 20.31157117, 21.4353635 ,
       18.53971968, 17.18572611, 20.74934949, 22.64791346, 19.77000977,
       20.64745349, 26.52652691, 20.77440554, 20.71546432, 25.17461484,
       20.4273652 , 23.37862521, 23.69454145, 20.33202239, 20.79378139,
       21.92024414, 22.47432006, 20.55884635, 16.36300764, 20.56342111,
       22.48570454, 14.61264839, 15.1802607 , 18.93828443, 14.0574955 ,
       20.03651959, 19.41306288, 20.06401034, 15.76005772, 13.24771577,
       17.26167729, 15.87759672, 19.36145104, 13.81270814, 16.44782934,
       13.56511101,  3.98343974, 14.59241207, 12.14503093,  8.72407108,
       12.00815659, 15.80308586,  8.50963929,  9.70965512, 14.79848067,
       20.83598096, 18.30017013, 20.12575267, 17.27585681, 22.35997992,
       20.07985184, 13.59903744, 33.26635221, 29.03938379, 25.56694529,
       32.71732164, 36.78111388, 40.56615533, 41.85122271, 24.79875684,
       25.3771545 , 37.20662185, 23.08244608, 26.40326834, 26.65647433,
       22.55412919, 24.2970948 , 22.98024802, 29.07488389, 26.52620066,
       30.72351225, 25.61835359, 29.14203283, 31.43690634, 32.9232938 ,
       34.72096487, 27.76792733, 33.88992899, 30.99725805, 22.72124288,
       24.76567683, 35.88131719, 33.42696242, 32.41513625, 34.51611818,
       30.76057666, 30.29169893, 32.92040221, 32.11459912, 31.56133385,
       40.84274603, 36.13046343, 32.66639271, 34.70558647, 30.09276228,
       30.64139724, 29.29189704, 37.07062623, 42.02879611, 43.18582722,
       22.6923888 , 23.68420569, 17.85435295, 23.49543857, 17.00872418,
       22.39535066, 17.06152243, 22.74106824, 25.21974252, 11.10601161,
       24.51300617, 26.60749026, 28.35802444, 24.91860458, 29.69254951,
       33.18492755, 23.77145523, 32.14086508, 29.74802362, 38.36605632,
       39.80716458, 37.58362546, 32.39769704, 35.45048257, 31.23446481,
       24.48478321, 33.28615723, 38.04368164, 37.15737267, 31.71297469,
       25.26658017, 30.101515  , 32.71897655, 28.42735376, 28.42999168,
       27.2913215 , 23.74446671, 24.11878941, 27.40241209, 16.32993575,
       13.39695213, 20.01655581, 19.86205904, 21.28604604, 24.07796482,
       24.20603792, 25.04201534, 24.91709097, 29.93762975, 23.97709054,
       21.69931969, 37.51051381, 43.29459357, 36.48121427, 34.99129701,
       34.80865729, 37.16296374, 40.9823638 , 34.44211691, 35.83178068,
       28.24913647, 31.22022312, 40.83256202, 39.31768808, 25.71099424,
       22.30344878, 27.20551341, 28.51386352, 35.47494122, 36.11110647,
       33.80004807, 35.61141951, 34.84311742, 30.35359323, 35.31260262,
       38.79684808, 34.33296541, 40.34038636, 44.67339923, 31.5955473 ,
       27.35994642, 20.09520596, 27.04518524, 27.21674397, 26.91105226,
       33.43602979, 34.40228785, 31.83374181, 25.82416035, 24.43687139,
       28.46348891, 27.36916176, 19.54441878, 29.11480679, 31.90852699,
       30.77325183, 28.9430835 , 28.88108106, 32.79876794, 33.20356949,
       30.76568546, 35.55843485, 32.70725436, 28.64759861, 23.59388439,
       18.5461558 , 26.88429024, 23.28485442, 25.55002201, 25.48337323,
       20.54343769, 17.61406384, 18.37627933, 24.29187594, 21.3257202 ,
       24.88826131, 24.87143049, 22.87255605, 19.4540234 , 25.11948741,
       24.66816374, 23.68209656, 19.33951725, 21.17636041, 24.25306588,
       21.59311197, 19.98766667, 23.34079584, 22.13973959, 21.55349196,
       20.61808868, 20.1607571 , 19.28455466, 22.16593919, 21.24893735,
       21.42985456, 30.32874523, 22.04915396, 27.70610125, 28.54595004,
       16.54657063, 14.78278261, 25.27336772, 27.54088054, 22.14633467,
       20.46081206, 20.54472332, 16.88194391, 25.40066956, 14.32299547,
       16.5927403 , 19.63224597, 22.7117302 , 22.19946949, 19.1989151 ,
       22.66091019, 18.92059374, 18.22715359, 20.22444386, 37.47946099,
       14.29172583, 15.53697148, 10.82825817, 23.81134987, 32.64787163,
       34.61163401, 24.94604102, 26.00259724,  6.12085728,  0.78021126,
       25.311373  , 17.73465914, 20.22593282, 15.83834861, 16.83742401,
       14.43123608, 18.47647773, 13.42427933, 13.05677824,  3.27646485,
        8.05936467,  6.13903114,  5.62271213,  6.44935154, 14.20597451,
       17.21022671, 17.29035065,  9.89064351, 20.21972222, 17.94511052,
       20.30017588, 19.28790318, 16.33300008,  6.56843662, 10.87541577,
       11.88704097, 17.81098929, 18.25461066, 12.99282707,  7.39319053,
        8.25609561,  8.07899971, 19.98563715, 13.69651744, 19.83511412,
       15.2345378 , 16.93112419,  1.69347406, 11.81116263, -4.28300934,
        9.55007844, 13.32635521,  6.88351077,  6.16827417, 14.56933235,
       19.59292932, 18.1151686 , 18.52011987, 13.13707457, 14.59662601,
        9.8923749 , 16.31998048, 14.06750301, 14.22573568, 13.00752251,
       18.13277547, 18.66645496, 21.50283795, 17.00039379, 15.93926602,
       13.32952716, 14.48949211,  8.78366731,  4.8300317 , 13.06115528,
       12.71101472, 17.2887624 , 18.73424906, 18.05271013, 11.49855612,
       13.00841512, 17.66975577, 18.12342294, 17.51503231, 17.21307203,
       16.48238543, 19.40079737, 18.57392951, 22.47833186, 15.24179836,
       15.78327609, 12.64853778, 12.84121049, 17.17173661, 18.50906858,
       19.02803874, 20.16441773, 19.76975335, 22.42614937, 20.31750314,
       17.87618837, 14.3391341 , 16.93715603, 16.98716629, 18.59431701,
       20.16395155, 22.97743546, 22.45110639, 25.5707207 , 16.39091112,
       16.09765427, 20.52835689, 11.5429045 , 19.20387482, 21.86820603,
       23.47052203, 27.10034494, 28.57064813, 21.0839881 , 19.4490529 ,
       22.2189221 , 19.65423066, 21.324671  , 11.86231364,  8.22260592,
        3.65825168, 13.76275951, 15.93780944, 20.62730097, 20.61035443,
       16.88048035, 14.01017244, 19.10825534, 21.29720741, 18.45524217,
       20.46764235, 23.53261729, 22.37869798, 27.62934247, 26.12983844,
       22.34870269])

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
xtrain , xtest , ytrain , ytest = train_test_split(boston.data,boston.target)

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
scaler=StandardScaler()
scaler.fit(xtrain)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [21]:
xtrain_scaled = scaler.transform(xtrain)
xtest_scaled=scaler.transform(xtest)

In [22]:
df3 = pd.DataFrame(xtrain_scaled)
df3.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12
count,3.790000e+02,3.790000e+02,3.790000e+02,3.790000e+02,3.790000e+02,3.790000e+02,3.790000e+02,3.790000e+02,3.790000e+02,3.790000e+02,3.790000e+02,3.790000e+02,3.790000e+02
mean,4.722110e-16,1.950946e-16,2.516603e-15,7.323371e-18,2.964501e-16,6.275250e-15,4.552207e-16,1.196346e-15,2.372772e-16,1.904076e-16,1.924933e-14,6.165107e-15,-3.180540e-16
std,1.001322e+00,1.001322e+00,1.001322e+00,1.001322e+00,1.001322e+00,1.001322e+00,1.001322e+00,1.001322e+00,1.001322e+00,1.001322e+00,1.001322e+00,1.001322e+00,1.001322e+00
min,-4.566501e-01,-4.931554e-01,-1.546654e+00,-2.713934e-01,-1.457991e+00,-3.550491e+00,-2.313187e+00,-1.243055e+00,-9.633664e-01,-1.304320e+00,-2.693781e+00,-3.688998e+00,-1.539586e+00
25%,-4.460723e-01,-4.931554e-01,-8.707364e-01,-2.713934e-01,-9.133808e-01,-5.587306e-01,-8.372052e-01,-7.985635e-01,-6.168471e-01,-7.572826e-01,-6.664549e-01,2.233540e-01,-7.868907e-01
50%,-4.261408e-01,-4.931554e-01,-1.976771e-01,-2.713934e-01,-1.353667e-01,-1.072695e-01,3.107805e-01,-3.018591e-01,-5.013406e-01,-4.540338e-01,2.550570e-01,3.871588e-01,-1.862831e-01
75%,5.746159e-03,1.554542e-01,9.741033e-01,-2.713934e-01,6.080690e-01,4.712804e-01,9.032892e-01,6.310421e-01,1.693282e+00,1.543841e+00,8.079642e-01,4.354563e-01,6.037305e-01
max,9.023279e+00,3.760022e+00,2.351660e+00,3.684688e+00,2.743285e+00,3.715741e+00,1.111373e+00,3.925087e+00,1.693282e+00,1.811413e+00,1.637325e+00,4.434277e-01,3.563817e+00

In [23]:
df4=pd.DataFrame(xtest_scaled)
df4.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12
count,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000
mean,0.175735,-0.039204,-0.083436,0.008959,0.035681,0.112140,0.012193,0.038272,0.096201,0.044498,0.016697,0.096685,-0.005476
std,1.655327,0.966713,0.915827,1.019155,1.006384,1.141706,0.970618,0.957088,1.019408,1.007772,0.989883,0.782385,1.022333
min,-0.456268,-0.493155,-1.438050,-0.271393,-1.380189,-3.996780,-2.140372,-1.222095,-0.963366,-1.268643,-2.509479,-3.520921,-1.359334
25%,-0.445586,-0.493155,-0.875023,-0.271393,-0.753456,-0.566119,-0.786066,-0.772387,-0.616847,-0.727552,-0.482153,0.214653,-0.810126
50%,-0.410097,-0.493155,-0.389163,-0.271393,-0.256391,0.030164,0.338995,-0.187752,-0.501341,-0.323221,0.301133,0.384762,-0.180650
75%,0.145433,0.038492,0.974103,-0.271393,0.737738,0.758708,0.839806,0.700902,1.693282,1.543841,0.807964,0.443428,0.600210
max,11.962324,3.547363,1.515694,3.684688,2.743285,3.634463,1.111373,2.560501,1.693282,1.543841,1.268720,0.443428,3.113186